import ColorBox from "./ColorBox";
import "./ColorBoxGrid.css"

//we invoke "colors" from the array of colors in App.jsx
export default function ColorBoxGrid ({ colors }){
    //boxes at first comes empty
    const boxes = [];
    //then we fill them with random colors generated by the loop
    for (let i = 0; i < 25; i++) {
        //we push the new colors into our "ColorBox" made in ColorBox.jsx
        boxes.push(<ColorBox colors={colors} />);
    }
    //return the variable "boxes" once filled 
    return <div className="ColorBoxGrid">{boxes}</div>;
}